server:
  port: 8080

spring:
  application:
    name: api
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  exchange:
    fanout: "votings.v1.vote-created"
